server:
  port: 9999

spring:
  application:
    name: MSA-Cafe-Turbine-Server

  #Config Server
  cloud:
    config:
      uri: http://localhost:8888
      name: MSA-Cafe-Config-Server

#Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/

#Turbine Server
turbine:
  appConfig: MSA-Service-Order, MSA-Service-Member, MSA-Service-Status
  clusterNameExpression: new String("default")